services:
  plane_proxy:
    build:
      context: ..
      dockerfile: mcp_servers/Dockerfile
    image: mcp-stack:latest
    command: ["python", "mcp_servers/plane_orig_transport_proxy.py"]
    network_mode: "host"

  plane_main:
    build:
      context: ..
      dockerfile: mcp_servers/Dockerfile
    image: mcp-stack:latest
    command: ["python", "mcp_servers/plane_mcp.py"]
    network_mode: "host"

  rocketchat:
    build:
      context: ..
      dockerfile: mcp_servers/Dockerfile
    image: mcp-stack:latest
    command: ["python", "mcp_servers/rocket_chat_mcp.py"]
    network_mode: "host"

  owncloud:
    build:
      context: ..
      dockerfile: mcp_servers/Dockerfile
    image: mcp-stack:latest
    command: ["python", "mcp_servers/webdav_mcp.py"]
    network_mode: "host"

  gitlab_openai:
    build:
      context: ..
      dockerfile: mcp_servers/Dockerfile
    image: mcp-stack:latest
    command: ["python", "mcp_servers/gitlab_openapi.py"]
    network_mode: "host"

  gitlab_transport_proxy:
    build:
      context: ..
      dockerfile: mcp_servers/Dockerfile
    image: mcp-stack:latest
    command: ["python", "mcp_servers/gitlab_transport_proxy.py"]
    network_mode: "host"

  gitlab_main:
    build:
      context: ..
      dockerfile: mcp_servers/Dockerfile
    image: mcp-stack:latest
    command: ["python", "mcp_servers/gitlab_mcp.py"]
    network_mode: "host"
