import os

os.environ["FASTMCP_EXPERIMENTAL_ENABLE_NEW_OPENAPI_PARSER"] = "true"

import asyncio
import hashlib
import json
import sys
from collections import defaultdict
from contextlib import contextmanager
from pathlib import Path

import httpx
import requests
import yaml
from fastmcp import FastMCP
from fastmcp.tools import Tool
from fastmcp.tools.tool_transform import ArgTransform, forward_raw

sys.path.append(Path(__file__).parent.as_posix())
import mcp_configs

USER_ID = "PLACEHOLDER"
AUTH_TOKEN = "PLACEHOLDER"


@contextmanager
def server_duplicate_behavior(curr_server, new_behavior):
    old_behavior = curr_server._tool_manager.duplicate_behavior

    curr_server._tool_manager.duplicate_behavior = new_behavior
    try:
        yield
    finally:
        curr_server._tool_manager.duplicate_behavior = old_behavior


def load_yaml(file: str | Path):
    with open(file, "r") as f:
        obj = yaml.load(f, Loader=yaml.CSafeLoader)
    return obj


def add_llm_generated_descs(spec: dict) -> dict:
    """Replaces original summary and description with the ones generated by an LLM."""
    llm_desc_path = (
        Path(__file__)
        .parents[1]
        .joinpath("data/api_specs/rocket_chat_openapi_specs/gpt41_descriptions.jsonl")
    )
    llm_descs = defaultdict(dict)
    with open(llm_desc_path, "r") as f:
        for line in f:
            obj = json.loads(line)
            llm_descs[obj["input"]["path"]][obj["input"]["method"]] = {
                "summary": obj["output"]["summary"],
                "description": obj["output"]["description"],
            }

    for k, path_spec in spec["paths"].items():
        for req_type, req_spec in path_spec.items():
            if k in llm_descs and req_type in llm_descs[k]:
                if "summary" in req_spec:
                    spec["paths"][k][req_type]["summary"] = llm_descs[k][req_type][
                        "summary"
                    ]
                if "description" in req_spec:
                    spec["paths"][k][req_type]["description"] = llm_descs[k][req_type][
                        "description"
                    ]
    return spec


def add_summary_to_desc(spec: dict) -> dict:
    """Prepends the summary to description for each path in the OpenAPI spec."""
    for k, path_spec in spec["paths"].items():
        for req_type, req_spec in path_spec.items():
            if "summary" in req_spec and "description" in req_spec:
                new_desc = req_spec["summary"] + "\n\n" + req_spec["description"]
                spec["paths"][k][req_type]["description"] = new_desc
    return spec


def clean_operation_id(spec: dict) -> dict:
    """Remove api v1 from Operation ID field."""
    for k, path_spec in spec["paths"].items():
        for req_type, req_spec in path_spec.items():
            if "operationId" in req_spec:
                opid = req_spec["operationId"]
                opid = opid.replace("-api-v1-", "-").replace("-api-", "-")
                spec["paths"][k][req_type]["operationId"] = opid
    return spec


def remove_response_schema(spec: dict) -> dict:
    for path, path_data in spec["paths"].items():
        for method, method_data in path_data.items():
            if "responses" not in method_data:
                continue
            for resp, resp_data in method_data["responses"].items():
                if "content" not in resp_data:
                    continue
                for content, content_data in resp_data["content"].items():
                    if "schema" in content_data:
                        del spec["paths"][path][method]["responses"][resp]["content"][
                            content
                        ]["schema"]
    return spec


def llm_desc_with_combined_summary_desc(spec: dict) -> dict:
    spec = clean_operation_id(spec)
    spec = add_llm_generated_descs(spec)
    spec = add_summary_to_desc(spec)
    spec = remove_response_schema(spec)
    return spec


spec_processor = os.environ.get("ROCKET_CHAT_SPEC_PROCESS")

if spec_processor is None or spec_processor == "add_summary_to_desc":
    spec_processor = llm_desc_with_combined_summary_desc
else:
    raise ValueError(f"OpenAPI spec processor not recognized. I got '{spec_processor}'")


# fmt: off
spec_pardir = Path(__file__).parents[1].joinpath("data/api_specs/rocket_chat_openapi_specs/original")

client = httpx.AsyncClient(base_url=mcp_configs.TAC_SERVICES["rocketchat"]["url"].strip("/"))

cm_spec = load_yaml(spec_pardir / "content-management.yaml")
cm_spec = spec_processor(cm_spec)
mcp = FastMCP.from_openapi(openapi_spec=cm_spec, client=client, name="Rocket Chat content Management")

auth_mcp = None

integ_spec = load_yaml(spec_pardir / "integrations.yaml")
integ_spec = spec_processor(integ_spec)
integ_mcp = FastMCP.from_openapi(openapi_spec=integ_spec, client=client, name="Rocket Chat Integrations")

market_spec = load_yaml(spec_pardir / "marketplace-apps.yaml")
market_spec = spec_processor(market_spec)
market_mcp = FastMCP.from_openapi(openapi_spec=market_spec, client=client, name="Rocket Chat Marketplace Apps")

msg_spec = load_yaml(spec_pardir / "messaging.yaml")
msg_spec = spec_processor(msg_spec)
msg_mcp = FastMCP.from_openapi(openapi_spec=msg_spec, client=client, name="Rocket Chat Messaging")

msg_p2_spec = load_yaml(spec_pardir / "messaging_p2.yaml")
msg_p2_spec = spec_processor(msg_p2_spec)
msg_p2_mcp = FastMCP.from_openapi(openapi_spec=msg_p2_spec, client=client, name="Rocket Chat Messaging Part Two")

misc_spec = load_yaml(spec_pardir / "miscellaneous.yaml")
misc_spec = spec_processor(misc_spec)
misc_mcp = FastMCP.from_openapi(openapi_spec=misc_spec, client=client, name="Rocket Chat Miscellaneous")

notif_spec = load_yaml(spec_pardir / "notifications.yaml")
notif_spec = spec_processor(notif_spec)
notif_mcp = FastMCP.from_openapi(openapi_spec=notif_spec, client=client, name="Rocket Chat Notifications")

oc_spec = load_yaml(spec_pardir / "omnichannel.yaml")
oc_spec = spec_processor(oc_spec)
oc_mcp = FastMCP.from_openapi(openapi_spec=oc_spec, client=client, name="Rocket Chat Omnichannel")

rooms_spec = load_yaml(spec_pardir / "rooms.yaml")
rooms_spec = spec_processor(rooms_spec)
rooms_mcp = FastMCP.from_openapi(openapi_spec=rooms_spec, client=client, name="Rocket Chat Rooms")

rooms_p2_spec = load_yaml(spec_pardir / "rooms_p2.yaml")
rooms_p2_spec = spec_processor(rooms_p2_spec)
rooms_p2_mcp = FastMCP.from_openapi(openapi_spec=rooms_p2_spec, client=client, name="Rocket Chat Rooms Part Two")

settings_spec = load_yaml(spec_pardir / "settings.yaml")
settings_spec = spec_processor(settings_spec)
settings_mcp = FastMCP.from_openapi(openapi_spec=settings_spec, client=client, name="Rocket Chat Settings")

stats_spec = load_yaml(spec_pardir / "statistics.yaml")
stats_spec = spec_processor(stats_spec)
stats_mcp = FastMCP.from_openapi(openapi_spec=stats_spec, client=client, name="Rocket Chat Statistics")

user_manage_spec = load_yaml(spec_pardir / "user-management.yaml")
user_manage_spec = spec_processor(user_manage_spec)
user_manage_mcp = FastMCP.from_openapi(openapi_spec=user_manage_spec, client=client, name="Rocket Chat User Management")

# fmt: on

if auth_mcp is not None:
    asyncio.run(mcp.import_server(auth_mcp))
asyncio.run(mcp.import_server(integ_mcp))
asyncio.run(mcp.import_server(market_mcp))
asyncio.run(mcp.import_server(msg_mcp))
asyncio.run(mcp.import_server(msg_p2_mcp))
asyncio.run(mcp.import_server(misc_mcp))
asyncio.run(mcp.import_server(notif_mcp))
asyncio.run(mcp.import_server(oc_mcp))
asyncio.run(mcp.import_server(rooms_mcp))
asyncio.run(mcp.import_server(rooms_p2_mcp))
asyncio.run(mcp.import_server(settings_mcp))
asyncio.run(mcp.import_server(stats_mcp))
asyncio.run(mcp.import_server(user_manage_mcp))


def refresh_creds():
    global USER_ID
    global AUTH_TOKEN
    base_url = mcp_configs.TAC_SERVICES["rocketchat"]["url"].strip("/")
    try:
        response = requests.post(
            f"{base_url}/api/v1/login",
            json={"resume": AUTH_TOKEN},
            headers={"Content-Type": "application/json"},
        )
        response.raise_for_status()
    except requests.HTTPError as err:
        if err.response.status_code == 401:
            res = requests.post(
                f"{base_url}/api/v1/login",
                data={
                    "user": mcp_configs.TAC_SERVICES["rocketchat"]["username"],
                    "password": mcp_configs.TAC_SERVICES["rocketchat"]["password"],
                },
            )
            res = res.json()["data"]
            USER_ID = res["userId"]
            AUTH_TOKEN = res["authToken"]
        else:
            raise err


def get_user_id():
    refresh_creds()
    global USER_ID
    return USER_ID


def get_auth_token():
    refresh_creds()
    global AUTH_TOKEN
    return AUTH_TOKEN


async def get_directory_replacement(**kwargs):
    query = {}
    for k, v in kwargs.items():
        if k == "query" or v is None:
            continue
        query[k] = v
    kwargs = {
        "query": json.dumps(query),
        "X-User-Id": get_user_id(),
        "X-Auth-Token": get_auth_token(),
    }
    return await forward_raw(**kwargs)


all_tools = asyncio.run(mcp.get_tools())
for tool in all_tools.values():
    params = tool.parameters["properties"]
    transform_args = {}
    if "X-User-Id" in params:
        transform_args["X-User-Id"] = ArgTransform(
            default_factory=get_user_id, hide=True
        )
    if "X-Auth-Token" in params:
        transform_args["X-Auth-Token"] = ArgTransform(
            default_factory=get_auth_token, hide=True
        )
    if "x-2fa-method" in params:
        transform_args["x-2fa-method"] = ArgTransform(default="password", hide=True)
    if "x-2fa-code" in params:
        transform_args["x-2fa-code"] = ArgTransform(
            default="7d6fa3f6044d86066927820333cf8e35eb1eef9a125f4cf9fc560c8a38fb9464",
            hide=True,
        )
    from_tool_kwargs = {}
    if len(transform_args):
        from_tool_kwargs["transform_args"] = transform_args
    if len(tool.name) >= 53:
        name_hash = hashlib.sha256(tool.name.encode()).hexdigest()[:8]
        new_name = name_hash + tool.name[-45:]
        from_tool_kwargs["name"] = new_name
    if "get_directory" in tool.name.lower():
        from_tool_kwargs["transform_fn"] = get_directory_replacement
        _targs = from_tool_kwargs.get("transform_args", {})
        _targs["query"] = ArgTransform(hide=True, default=json.dumps({}))
        from_tool_kwargs["transform_args"] = _targs
    if len(from_tool_kwargs):
        new_tool = Tool.from_tool(tool, **from_tool_kwargs)
        with server_duplicate_behavior(mcp, "replace"):
            mcp.add_tool(new_tool)
        if "name" in from_tool_kwargs:
            mcp.remove_tool(tool.name)

if __name__ == "__main__":
    mcp.run(transport="sse", port=mcp_configs.ALL_SERVER_PORTS["rocketchat"])
