#!/usr/bin/env bash

if [[ -z "${CONFIG_FILE}" ]]; then
    echo 'You have to set the "CONFIG_FILE" env var.'
    exit 1
fi

bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 1 --end 1
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 2 --end 2
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 3 --end 3
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 4 --end 4
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 5 --end 5
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 6 --end 6
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 7 --end 7
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 8 --end 8
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 9 --end 9
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 10 --end 10
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 11 --end 11
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 12 --end 12
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 13 --end 13
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 14 --end 14
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 15 --end 15
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 16 --end 16
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 17 --end 17
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 18 --end 18
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 19 --end 19
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 20 --end 20
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 21 --end 21
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 22 --end 22
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 23 --end 23
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 24 --end 24
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 25 --end 25
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 26 --end 26
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 27 --end 27
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 28 --end 28
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 29 --end 29
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 30 --end 30
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 31 --end 31
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 32 --end 32
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 33 --end 33
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 34 --end 34
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 35 --end 35
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 36 --end 36
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 37 --end 37
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 38 --end 38
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 39 --end 39
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 40 --end 40
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 41 --end 41
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 42 --end 42
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 43 --end 43
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 44 --end 44
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 45 --end 45
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 46 --end 46
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 47 --end 47
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 48 --end 48
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 49 --end 49
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 50 --end 50
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 51 --end 51
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 52 --end 52
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 53 --end 53
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 54 --end 54
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 55 --end 55
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 56 --end 56
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 57 --end 57
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 58 --end 58
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 59 --end 59
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 60 --end 60
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 61 --end 61
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 62 --end 62
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 63 --end 63
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 64 --end 64
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 65 --end 65
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 66 --end 66
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 67 --end 67
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 68 --end 68
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 69 --end 69
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 70 --end 70
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 71 --end 71
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 72 --end 72
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 73 --end 73
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 74 --end 74
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 75 --end 75
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 76 --end 76
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 77 --end 77
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 78 --end 78
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 79 --end 79
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 80 --end 80
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 81 --end 81
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 82 --end 82
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 83 --end 83
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 84 --end 84
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 85 --end 85
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 86 --end 86
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 87 --end 87
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 88 --end 88
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 89 --end 89
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 90 --end 90
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 91 --end 91
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 92 --end 92
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 93 --end 93
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 94 --end 94
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 95 --end 95
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 96 --end 96
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 97 --end 97
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 98 --end 98
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 99 --end 99
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 100 --end 100
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 101 --end 101
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 102 --end 102
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 103 --end 103
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 104 --end 104
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 105 --end 105
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 106 --end 106
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 107 --end 107
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 108 --end 108
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 109 --end 109
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 110 --end 110
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 111 --end 111
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 112 --end 112
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 113 --end 113
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 114 --end 114
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 115 --end 115
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 116 --end 116
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 117 --end 117
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 118 --end 118
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 119 --end 119
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 120 --end 120
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 121 --end 121
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 122 --end 122
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 123 --end 123
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 124 --end 124
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 125 --end 125
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 126 --end 126
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 127 --end 127
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 128 --end 128
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 129 --end 129
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 130 --end 130
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 131 --end 131
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 132 --end 132
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 133 --end 133
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 134 --end 134
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 135 --end 135
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 136 --end 136
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 137 --end 137
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 138 --end 138
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 139 --end 139
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 140 --end 140
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 141 --end 141
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 142 --end 142
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 143 --end 143
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 144 --end 144
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 145 --end 145
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 146 --end 146
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 147 --end 147
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 148 --end 148
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 149 --end 149
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 150 --end 150
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 151 --end 151
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 152 --end 152
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 153 --end 153
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 154 --end 154
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 155 --end 155
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 156 --end 156
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 157 --end 157
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 158 --end 158
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 159 --end 159
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 160 --end 160
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 161 --end 161
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 162 --end 162
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 163 --end 163
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 164 --end 164
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 165 --end 165
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 166 --end 166
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 167 --end 167
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 168 --end 168
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 169 --end 169
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 170 --end 170
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 171 --end 171
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 172 --end 172
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 173 --end 173
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 174 --end 174
bash evaluation/benchmarks/agc/scripts/run_infer.sh --config-file "${CONFIG_FILE}" --start 175 --end 175
