[core]
default_agent='CodeActAgent'
file_store='memory'

[llm.agent]
model="litellm_proxy/gpt-4.1"
api_key="sk-1234"
base_url="http://localhost:4000"
disable_vision=true
log_completions=true
log_completions_folder="exp_artifacts/log_cmp_agent"

[llm.env]
model="gpt-4.1"
api_key="sk-1234"
base_url="http://localhost:4000"
disable_vision=true
log_completions=true
log_completions_folder="exp_artifacts/log_cmp_env"

# [mcp]
# sse_servers = ["http://localhost:7879/sse"]

[agent]
enable_prompt_extensions=false
enable_mcp=true
# system_prompt_filename='system_prompt_cua.j2'
# system_prompt_filename='system_prompt_gt_tools.j2'
# system_prompt_filename='system_prompt_find_tools.j2'
# enable_browsing=false
